version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./firebase-adminsdk.json:/app/firebase-adminsdk.json:ro
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=http://backend:8000
    depends_on:
      - backend
