[theme]
base = "light"
primaryColor = "#4F46E5"
backgroundColor = "#E9EBF0"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#14161A"
borderColor = "#E9EAEC"
baseRadius = "large"
buttonRadius = "large"
showWidgetBorder = true
showSidebarBorder = false
linkUnderline = false

font = "sans-serif"

greenColor = "#4B5563"
redColor = "#14161A"
orangeColor = "#9CA3AF"
blueColor = "#4F46E5"
violetColor = "#4F46E5"
grayColor = "#9CA3AF"

chartCategoricalColors = ["#14161A", "#4B5563", "#9CA3AF", "#4F46E5", "#2A2E35"]

[theme.sidebar]
backgroundColor = "#E9EBF0"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#14161A"
borderColor = "#E9EAEC"
primaryColor = "#4F46E5"

[server]
headless = true
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false
address = "localhost"

[browser]
gatherUsageStats = false
